<?php 
   include ("myadmin/banco.php");
  header('Content-Type: text/html; charset=ISO-8859-1');      
  //
  $con = RetornaConexaoMysql('magocomercial', 'magocomercial_com_br');
  header('Content-Type: text/html; charset=ISO-8859-1');   
  //
  error_reporting(0);
  $colcount = 0;
  //
  $sqlStr = "SELECT id_document, name_document, descript, url_document from tbl_documents";
  $query = mysql_query($sqlStr);
?> 
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
<div align=center id="context">  
<script src="js/jquery.nicescroll.js"></script>
<link rel="stylesheet" type="text/css" href="css/nanoscroller.css" />
<link rel="stylesheet" type="text/css" href="css/nanostyle.css" />
<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="js/jquery.nanoscroller.min.js"></script>
<script>
 	
    $(document).ready((function($) { 
      $('.nano').nanoScroller();
      $('.nano').nanoScroller({ alwaysVisible: true, scroll: 'top' });	
 
    });
     	
</script>

  <div align=center id="Imageapp">
     <div id="sliderWrapp" style="//border:1px solid green;position:relative;height:330px;">
		   <!-- Start cssSlider.com -->
		   <!-- Generated by cssSlider.com 2.0 -->
		   <!--[if IE]><link rel="stylesheet" href="css/ie.css"><![endif]-->
		   <!--[if lte IE 9]><script type="text/javascript" src="js/ie.js"></script><![endif]-->
		   <div class='csslider1 autoplay ' style="//border: 1px solid black;">
   		   <input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide' >
		     <input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide' >
		     <input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide' >
		     <input name="cs_anchor1" id='cs_slide1_3' type="radio" class='cs_anchor slide' >
		     <input name="cs_anchor1" id='cs_slide1_4' type="radio" class='cs_anchor slide' >
		     <input name="cs_anchor1" id='cs_play1'    type="radio" class='cs_anchor' checked>
		     <input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'>
		     <input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'>
		     <input name="cs_anchor1" id='cs_pause1_2' type="radio" class='cs_anchor pause'>
		     <input name="cs_anchor1" id='cs_pause1_3' type="radio" class='cs_anchor pause'>
		     <input name="cs_anchor1" id='cs_pause1_4' type="radio" class='cs_anchor pause'>
		     <ul>
			     <li class="cs_skeleton"><img src="img/ong-caopartilhe-loadera.jpg" style="max-width:1680px;" /></li>
			     <li class='num0 img slide'><img src="img/ong-caopartilhe-loadera.jpg" style="max-width:1680px;" /></li>
			     <li class='num1 img slide'><img src="img/ong-caopartilhe-loaderb.jpg" style="max-width:1680px;" /></li>
			     <li class='num2 img slide'><img src="img/ong-caopartilhe-loaderc.jpg" style="max-width:1680px;" /></li>
			     <li class='num3 img slide'><img src="img/ong-caopartilhe-loaderd.jpg" style="max-width:1680px;" /></li>
			     <li class='num4 img slide'><img src="img/ong-caopartilhe-loadere.jpg" style="max-width:1680px;" /></li>
		     </ul>
		   </div>
		   <!-- End cssSlider.com -->
     </div>
  </div>
  <div align=center id="ajaxdiv">
    <div align=left style="//border: 1px solid brown; width: 850px; height: 330px;">
        <div align=left style="//border: 1px solid red;font-size:22px;position:relative;width:840px;color:#710c07;top:5px;">
          PRESTAÃ??Ã??O DE CONTAS
        </div>
      <div class="nano" style="//border: 1px solid red;width:520px;height:270px;top:20px;">
       <div class="nano-content" style="//border:1px solid blue;">
            <div align=justify style="//border: 1px solid green;font-size:12px;color:#710c07;position:relative;float:left;width:490px;">
              Para a CÃ£opartilhe, uma entidade do terceiro setor tem um papel relevante para a sociedade civil e precisa ser caracterizado por aÃ?Â§Ã?Âµes de solidariedade e pelo legÃ?Â­timo cumprimento de obrigaÃ?Â§Ã?Âµes sociais.  Pensando nisso e querendo tornar o empenho o mais transparente possÃ?Â­vel, uma prestaÃ?Â§Ã?Â£o de contas Ã?Â©, mensalmente, disponibilizada aqui. Estamos Ã?Â  disposiÃ?Â§Ã?Â£o para esclarecer qualquer dÃ?Âºvida!
              <p>Mensalmente disponibilizamos a prestaÃ?Â§Ã?Â£o de contas do mÃ?Âªs anterior. Caso queira ver as contas dos meses e anos passados, envie um emails solicitando.
            </div>
            <div align=left style="//border:1px solid blue;position:relative;width:490px;">
              <table border=0 cellspacing=1 width=400>
              <?php
                while($prod = mysql_fetch_array($query)) {
              ?>
              <tr><td><img src="img/ong-caopartilhe-pdf.GIF"></td><td><a href="<?php echo $prod['url_document']; ?>"><?php echo $prod['name_document']?></a></td></tr>
              
              <?php
              }
              ?>
             
              </table>
            </div>
         </div>
       </div>
       <div align=center style="//border: 1px solid blue;position:relative;float:left;left:20px;width:310px;top:30px;">
          <img src="img/ong-caopartilhe-prestacao-de-contas.jpg">
       </div>
 
    </div>    


</div>

</body>
</html>
<?php
  mysql_close($con);
?>