<?php 
   include ("myadmin/banco.php");
  header('Content-Type: text/html; charset=ISO-8859-1');      
  //
  $con = RetornaConexaoMysql('magocomercial', 'magocomercial_com_br');
  header('Content-Type: text/html; charset=ISO-8859-1');   
  //
  error_reporting(0);
  $colcount = 0;
  //
  $sqlStr = "SELECT id_document, name_document, descript, url_document from tbl_documents";
  $query = mysql_query($sqlStr);
?> 
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
<div align=center id="context">  
<script src="js/jquery.nicescroll.js"></script>
<link rel="stylesheet" type="text/css" href="css/nanoscroller.css" />
<link rel="stylesheet" type="text/css" href="css/nanostyle.css" />
<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="js/jquery.nanoscroller.min.js"></script>
<script>
 	
    $(document).ready((function($) { 
      $('.nano').nanoScroller();
      $('.nano').nanoScroller({ alwaysVisible: true, scroll: 'top' });	
 
    });
     	
</script>

  <div align=center id="Imageapp">
     <div id="sliderWrapp" style="//border:1px solid green;position:relative;height:330px;">
		   <!-- Start cssSlider.com -->
		   <!-- Generated by cssSlider.com 2.0 -->
		   <!--[if IE]><link rel="stylesheet" href="css/ie.css"><![endif]-->
		   <!--[if lte IE 9]><script type="text/javascript" src="js/ie.js"></script><![endif]-->
	


</div>

</body>
</html>
<?php
  mysql_close($con);
?>